version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  ingest-api:
    # Use the published image and tag from DockerHub
    image: hubmap/ingest-api:${INGEST_API_VERSION:?err}
    volumes:
      # Mount conf.d-prod to the nginx conf.d on container
      - "./ingest-api/nginx/conf.d-prod:/etc/nginx/conf.d"
      # Mount Globus data
      - "/hive/hubmap:/hive/hubmap"

  ingest-api-rq-dashboard:
    image: jaredv/rq-docker:0.0.2
    hostname: ingest-api-rq-dashboard
    container_name: ingest-api-rq-dashboard
    command: rq-dashboard -H ingest-api-rq-server
    ports:
      - 9181:9181
    depends_on:
      - ingest-api-rq-worker
    networks:
      - hubmap

  ingest-api-rq-worker:
    image: jaredv/rq-docker:0.0.2
    hostname: ingest-api-rq-worker
    container_name: ingest-api-rq-worker
    # Use port 6379 exposed on the container not host
    command: rq worker -u redis://ingest-api-rq-server:6379 high normal low
    deploy:
      replicas: 1
    depends_on:
      - ingest-api-rq-server
    networks:
      - hubmap

  ingest-api-rq-server:
    image: redis:alpine
    hostname: ingest-api-rq-server
    container_name: ingest-api-rq-server
    networks:
      - hubmap
